apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
    - name: http-query
      port: 16686
      targetPort: 16686
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.56
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4317
            - containerPort: 16686
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: observability
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: http
      port: 16686
      targetPort: 16686
  type: ClusterIP
