apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    istio-injection: enabled
