enableServiceLinks: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.logging.svc.cluster.local:3100
        isDefault: true
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query.observability:16686

env:
  GF_TRACING_ENABLED: "false"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  # Override any service-provided Jaeger env vars that might trigger client init
  JAEGER_AGENT_HOST: ""
  JAEGER_AGENT_PORT: ""
  # Install legacy Loki Explore app to satisfy Drilldown->Logs route
  GF_INSTALL_PLUGINS: grafana-lokiexplore-app

grafana.ini:
  tracing:
    enabled: false
