allInOne:
  enabled: true
  # all-in-one exposes query and collector in one pod
  collector:
    otlp:
      enabled: true

storage:
  type: memory

provisionDataStore:
  cassandra: false

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false
