zookeeper:
  enabled: true

listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

advertisedListeners:
  - PLAINTEXT://kafka.data.svc.cluster.local:9092

autoCreateTopicsEnable: true
