apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki

data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      instance_addr: 0.0.0.0
      path_prefix: /data/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      storage:
        filesystem:
          chunks_directory: /data/loki/chunks
          rules_directory: /data/loki/rules

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    ruler:
      storage:
        type: local
        local:
          directory: /data/loki/rules

    limits_config:
      volume_enabled: true
      max_streams_per_user: 2000
      allow_structured_metadata: false
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
  ports:
    - name: http
      port: 3100
      targetPort: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5.3
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/config.yaml
          ports:
            - name: http
              containerPort: 3100
          volumeMounts:
            - name: data
              mountPath: /data/loki
            - name: config
              mountPath: /etc/loki
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
