loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
    grpc_listen_port: 9096
  common:
    instance_addr: 127.0.0.1
    path_prefix: /loki
    storage:
      filesystem:
        chunks_directory: /loki/chunks
        rules_directory: /loki/rules
    replication_factor: 1
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory
  schema_config:
    configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
  ruler:
    alertmanager_url: http://localhost:9093
  limits_config:
    max_streams_per_user: 2000

promtail:
  enabled: true
  config:
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: dns:///loki.logging:9096
    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - json:
              expressions:
                traceId: traceId
                spanId: spanId
                service: service
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: ["__meta_kubernetes_pod_node_name"]
            target_label: "__host__"
          - action: replace
            source_labels: ["__meta_kubernetes_pod_uid"]
            target_label: "pod_uid"
          - action: replace
            source_labels: ["__meta_kubernetes_pod_name"]
            target_label: "pod"
          - action: replace
            source_labels: ["__meta_kubernetes_namespace"]
            target_label: "namespace"
          - action: replace
            source_labels: ["__meta_kubernetes_pod_container_name"]
            target_label: "container"
          - action: replace
            replacement: "/var/log/pods/*$1/*.log"
            separator: /
            regex: (.*)
            source_labels: ["pod_uid"]
            target_label: "__path__"
