replicaCount: 1

image:
  repository: k3d-registry.localhost:5000/playground/payment-service
  pullPolicy: Always
  tag: "1.0-SNAPSHOT"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  quarkusOtelExporterOtlpEndpoint: http://jaeger-collector.observability:4317
  mpMessagingIncomingOrdersInBootstrapServers: kafka.data.svc.cluster.local:9092
