apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: apps
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: k3d-registry.localhost:5000/playground/inventory-service:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger-collector.observability:4317
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: apps
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
